//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UHFReader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UHFREADER_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_INTERNET_DIALOG             129
#define IDD_SERIAL_DIALOG               130
#define IDD_SYSCONFIG_DIALOG            131
#define IDD_ISO180006B_DIALOG           132
#define IDD_EPCGEN2_DIALOG              133
#define IDB_SINGLE_BITMAP               134
#define IDB_NOSINGEL_BITMAP             135
#define IDB_LOGO_BITMAP                 137
#define IDD_FREQPOINTS_DIALOG           141
#define IDB_BITMAP_STATE                142
#define IDB_BITMAP_LIST                 143
#define IDD_CERTIFICATION_DIALOG        149
#define IDD_ANTCONFIG_DIALOG            154
#define IDD_DIALOG1                     156
#define IDD_DLG_SCAN                    156
#define IDC_CONNECT_TAB                 1002
#define IDC_EDIT1                       1004
#define IDC_TAGID_EDIT                  1004
#define IDC_EDIT_MPW                    1004
#define IDC_TRIGGERTIME_EDIT            1004
#define IDC_IP_PORT_EDIT                1004
#define IDC_EDIT2                       1006
#define IDC_ACCPW_EDIT                  1006
#define IDC_ASKPASSWORD_SINGLE_EDIT     1006
#define IDC_EDIT_PW                     1006
#define IDC_DELAYTIME_EDIT              1006
#define IDC_I_DISCONNECT_BUTTON         1007
#define IDC_ANTENNA3_EDIT               1007
#define IDC_INTERNET_DISCONNECT_BUTTON  1007
#define IDC_I_CONNECT_BUTTON            1008
#define IDC_ANTENNA2_EDIT               1008
#define IDC_INTERNET_CONNECT_BUTTON     1008
#define IDC_COMBO1                      1009
#define IDC_COMBAUD_COMBO               1009
#define IDC_ANTENNA4_EDIT               1009
#define IDC_MEMBANK_COMBO               1009
#define IDC_MEMBANK_SINGLE_COMBO        1009
#define IDC_TAGADDR_COMBO               1009
#define IDC_COMBO_LANGUAGE              1009
#define IDC_POWER_COMBO                 1009
#define IDC_LIST1                       1010
#define IDC_RESULT_LIST                 1010
#define IDC_LIST_SCAN                   1010
#define IDC_LIST2                       1011
#define IDC_MEMBANK_COMBO2              1011
#define IDC_SYSTEM_TAB                  1012
#define IDC_WRITEMEMBANK_COMBO          1012
#define IDC_BUTTON1                     1013
#define IDC_CLEARBUTTON                 1013
#define IDC_BUTTON_SET                  1013
#define IDC_BUTTON_CERTIFICATION        1013
#define IDC_SWITCH_BUTTON               1013
#define IDC_BTN_SCAN                    1013
#define IDC_BUTTON2                     1014
#define IDC_QUERYLOCK_BUTTON            1014
#define IDC_BUTTON_QUERY                1014
#define IDC_SETINTRFACE_BUTTON          1014
#define IDC_CONNECT_BUTTON              1014
#define IDC_SETRFPOWER_BUTTON           1015
#define IDC_ONCEINVENTORY_BUTTON        1015
#define IDC_GETFREQUENCY_BUTTON         1016
#define IDC_SETANTENNA_BUTTON           1017
#define IDC_GETANTENNA_BUTTON           1018
#define IDC_RESET_BUTTON                1019
#define IDC_SETSFTM_BUTTON              1020
#define IDC_SETANT_BUTTON               1020
#define IDC_GETSFTM_BUTTON              1021
#define IDC_GETANT_BUTTON               1021
#define IDC_GETVERSION_BUTTON           1022
#define IDC_OUTPORT_BUTTON              1023
#define IDC_SETTEST_BUTTON              1024
#define IDC_SETINTERNET_BUTTON          1025
#define IDC_GETINTERNET_BUTTON          1026
#define IDC_ANT2_CHECK                  1027
#define IDC_ANT1_CHECK                  1028
#define IDC_ANT3_CHECK                  1029
#define IDC_ANT4_CHECK                  1030
#define IDC_CHINA_RADIO                 1031
#define IDC_ANT6_CHECK                  1031
#define IDC_NORTHAMERICA_RADIO          1032
#define IDC_ANT5_CHECK                  1032
#define IDC_EUROPE_RADIO                1033
#define IDC_ANT7_CHECK                  1033
#define IDC_OTHERS_RADIO                1034
#define IDC_ANT8_CHECK                  1034
#define IDC_READVERSION_EDIT            1035
#define IDC_GETOUTPORT_BUTTON           1036
#define IDC_ANT10_CHECK                 1036
#define IDC_ANT9_CHECK                  1037
#define IDC_IPADDRESS                   1038
#define IDC_GATEWAY                     1039
#define IDC_MASKCODE                    1040
#define IDC_IOPORT1_RADIO               1041
#define IDC_ANT11_CHECK                 1041
#define IDC_IOPORT2_RADIO               1042
#define IDC_ANT12_CHECK                 1042
#define IDC_RELAY_RADIO                 1043
#define IDC_ANT14_CHECK                 1043
#define IDC_LOWLEVE_RADIO               1044
#define IDC_ANT13_CHECK                 1044
#define IDC_ANT15_CHECK                 1045
#define IDC_HIGHLEVE_RADIO              1046
#define IDC_ANT16_CHECK                 1046
#define IDC_MORETAG_RADIO               1048
#define IDC_LITERTAG_RADIO              1049
#define IDC_TAGMODE_EDIT                1050
#define IDC_OPENPA_RADIO1               1051
#define IDC_CLOSEPA_RADIO2              1052
#define IDC_ANTCORRECT_RADIO3           1053
#define IDC_COM_CONNECT_BUTTON          1055
#define IDC_COM_DISCONNECT_BUTTON       1056
#define IDC_COMSPORT_COMBO              1057
#define IDC_SETBAUD_COMBO               1058
#define IDC_SETBAUD_BUTTON              1059
#define IDC_ANTENNA1_EDIT               1060
#define IDC_GETRFPOWER_BUTTON           1061
#define IDC_SETFREQUENCY_BUTTON         1062
#define IDC_ENTER_BUTTON                1064
#define IDC_CANCEL_BUTTON               1065
#define IDC_TREE                        1068
#define IDC_ANT1_BITMAP                 1069
#define IDC_ANT2_BITMAP                 1070
#define IDC_ANT3_BITMAP                 1071
#define IDC_ANT4_BITMAP                 1072
#define IDC_INTERNETPORT_EDIT           1073
#define IDC_LOGINIP                     1074
#define IDC_ANT6_BITMAP                 1074
#define IDC_WORDADDR_COMBO              1075
#define IDC_ANT5_BITMAP                 1075
#define IDC_VALUE_EDIT                  1076
#define IDC_VALUE_SINGLE_EDIT           1076
#define IDC_ANT7_BITMAP                 1076
#define IDC_WORDADDR_COMBO2             1077
#define IDC_ANT8_BITMAP                 1077
#define IDC_SECREAD_BUTTON              1078
#define IDC_EXECUTE_BUTTON              1078
#define IDC_ANT10_BITMAP                1078
#define IDC_SECWRITE_BUTTON             1079
#define IDC_ANT9_BITMAP                 1079
#define IDC_SECREAD_RADIO               1080
#define IDC_ANT11_BITMAP                1080
#define IDC_SECWRITE_RADIO              1081
#define IDC_ANT12_BITMAP                1081
#define IDC_SECLOCK_RADIO               1082
#define IDC_ANT14_BITMAP                1082
#define IDC_KILLTAG_RADIO               1083
#define IDC_ANT13_BITMAP                1083
#define IDC_CONFIGTAG_RADIO             1084
#define IDC_ANT15_BITMAP                1084
#define IDC_SECLOCK_BUTTON              1085
#define IDC_ANT16_BITMAP                1085
#define IDC_KILLTAG_BUTTON              1086
#define IDC_CONFIG_BUTTON               1087
#define IDC_WRITEWORDADDR_COMBO         1088
#define IDC_LEVEL_COMBO                 1089
#define IDC_WORDCNT_COMBO               1090
#define IDC_WRITEWORDNUM_COMBO          1091
#define IDC_LENGTH_COMBO                1092
#define IDC_WRITEVALUE_EDIT             1096
#define IDC_YESMATCH_CHECK              1098
#define IDC_NOMATCH_CHECK               1099
#define IDC_MEMBANK_STATIC              1100
#define IDC_ACCPW_STATIC                1101
#define IDC_LEVEL_STATIC                1102
#define IDC_WORDADDR_STATIC             1103
#define IDC_WORDCNT_STATIC              1104
#define IDC_ACTION_STATIC               1105
#define IDC_LENGTH_STATIC               1106
#define IDC_VALUE_STATIC                1107
#define IDC_VALUE_SINGLE_STATIC         1107
#define IDC_MEMBANK_STATIC2             1108
#define IDC_WORDADDR_STATIC2            1109
#define IDC_MULTI_TAG_INVENTORY_RADIO   1110
#define IDC_MULTI_TAG_READ_RADIO        1111
#define IDC_MULTI_TAG_WRITE_RADIO       1112
#define IDC_RESERVE_CHECK               1113
#define IDC_EPC_CHECK                   1114
#define IDC_USER_CHECK                  1115
#define IDC_TID_CHECK                   1116
#define IDC_RESERVE_STARTADDR_COMBO     1117
#define IDC_EPC_STARTADDR_COMBO         1118
#define IDC_TID_STARTADDR_COMBO         1119
#define IDC_USER_STARTADDR_COMBO        1120
#define IDC_RESERVE_CNTNUM_COMBO        1121
#define IDC_EPC_CNTNUM_COMBO            1122
#define IDC_TID_CNTNUM_COMBO            1123
#define IDC_USER_CNTNUM_COMBO           1124
#define IDC_SELECTMEMBANK_STATIC        1125
#define IDC_STARTADDR_STATIC            1126
#define IDC_WORDCNTNUM_STATIC           1127
#define IDC_WRITEMEMBANK_STATIC         1128
#define IDC_WRITEWORDADDR_STATIC        1129
#define IDC_WRITEWORDNUM_STATIC         1130
#define IDC_WRITEVALUE_STATIC           1131
#define IDC_MULTIREAD_BUTTON            1134
#define IDC_MULTIWRITE_BUTTON           1135
#define IDC_STARTINVENTORY_BUTTON       1136
#define IDC_START_BUTTON                1136
#define IDC_STOPINVENTORY_BUTTON        1137
#define IDC_TAGDATA_LIST                1138
#define IDC_LIST                        1139
#define IDC_STOPREADTAG_BUTTON          1140
#define IDC_STOP_BUTTON                 1140
#define IDC_BUTTON_CLEAR                1141
#define IDC_CLEARSYSMSG_BUTTON          1145
#define IDC_STARTADDR_SINGLE_COMBO      1149
#define IDC_LENGTH_SINGLE_COMBO         1150
#define IDC_STARTADDR_SINGLE_STATIC     1151
#define IDC_MEMBANK_SINGLE_STATIC       1152
#define IDC_LENGTH_SINGLE_STATIC        1153
#define IDC_ASKPASSWPRD_SINGLE_STATIC   1154
#define IDC_LOCKLEVEL_SINGLE_STATIC     1155
#define IDC_LOCKLEVEL_SINGLE_COMBO      1156
#define IDC_MATCH_SINGLE_STATIC         1157
#define IDC_MATCH_SINGLE_COMBO          1158
#define IDC_LOCKMEMBANK_COMBO           1159
#define IDC_SINGLEREAD_RADIO            1161
#define IDC_SINGLEWRITE_RADIO           1162
#define IDC_SINGLELOCK_RADIO            1163
#define IDC_OPERATION_BUTTON            1164
#define IDC_UID_CHECK                   1166
#define IDC_MUTITAGIDENTIFY_RADIO       1167
#define IDC_MUTITAGREAD_RADIO           1168
#define IDC_READADDR_COMBO              1169
#define IDC_READADDR_STATIC             1170
#define IDC_CLEARRESULT_BUTTON          1171
#define IDC_TIME_STATIC                 1172
#define IDC_NUMBER_STATIC               1173
#define IDC_SPEED_COMBO                 1174
#define IDC_SPEED_STATIC                1175
#define IDC_EDIT_CTF                    1176
#define IDC_BUTTON_MANAGER              1177
#define IDC_STATIC_LOGIN                1178
#define IDC_STATIC_CERTIFICATION        1179
#define IDC_STATIC_SIX                  1180
#define IDC_STATIC_TBYTE                1181
#define IDC_STATIC_INFO                 1182
#define IDC_STATIC_MTITLE               1183
#define IDC_STATIC_SYSTEM               1184
#define IDC_STATIC_SIX2                 1184
#define IDC_STATIC_CONNECTTYPE          1185
#define IDC_SP_NUM_STATIC               1186
#define IDC_SP_BAUD_STATIC              1187
#define IDC_IP_ADDR_STATIC              1189
#define IDC_IP_PORT_STATIC              1190
#define IDC_MULTITAG_STATIC             1191
#define IDC_NUM_STATIC                  1192
#define IDC_TIMES_STATIC                1193
#define IDC_UNIQUETAG_STATIC            1194
#define IDC_SHOWDATA_STATIC             1195
#define IDC_TAGIDENTIFY_STATIC          1196
#define IDC_TIME1_STATIC                1197
#define IDC_ASKADDR_STATIC              1198
#define IDC_ASKID_STATIC                1199
#define IDC_RESULT_STATIC               1200
#define IDC_CMD_RADIO                   1202
#define IDC_ANIMATION_RADIO             1203
#define IDC_TRIGGER_RADIO               1204
#define IDC_RS485_CHECK                 1205
#define IDC_WEIGEN_CHECK                1206
#define IDC_RS232_CHECK                 1207
#define IDC_IP_CHECK                    1208
#define IDC_RELAY_CHECK                 1209
#define IDC_WEIGENSTYLE_COMBO           1210
#define IDC_QUERYINTERFACE_BUTTON       1212
#define IDC_TRIGGERTIME_STATIC          1213
#define IDC_STYLE_STATIC                1214
#define IDC_DELAYTIME_STATIC            1215
#define IDC_PORT_STATIC                 1216
#define IDC_GATWAY_STATIC               1217
#define IDC_MASK_STATIC                 1218
#define IDC_OUTPUT_STATIC               1219
#define IDC_MODEL_STATIC                1220
#define IDC_NOWMODEL_STATIC             1221
#define IDC_RATEFREQ_STATIC             1222
#define IDC_MODELINTERFACE_STATIC       1223
#define IDC_INTERNET_STATIC             1224
#define IDC_DELAYTIME_STATIC2           1225
#define IDC_SERIALNO_STATIC             1227
#define IDC_VERSION_STATIC              1228
#define IDC_IP_RADIO                    1229
#define IDC_SP_RADIO                    1230
#define IDC_IP_ADDR_IPADDRESS           1231
#define IDC_SP_NUM_COMBO                1232
#define IDC_SP_BAUD_COMBO               1233
#define IDC_DISCONNECT_BUTTON           1234
#define IDC_RESTART_BUTTON              1235
#define IDC_MAC_EDIT                    1236
#define IDC_SNO_EDIT                    1237
#define IDC_CHECK_MAC                   1238
#define IDC_CHECK_SNO                   1239
#define IDC_SETSNOMAC_BUTTON            1240
#define IDC_QUERYSNOMAC_BUTTON          1241
#define IDC_STATIC_SNO                  1242
#define IDC_STATIC_MAC                  1243
#define IDC_RADIO1                      1244
#define IDC_RADIO_AAOPEN                1244
#define IDC_RADIO2                      1245
#define IDC_RADIO_AACLOSE               1245
#define IDC_RADIO3                      1246
#define IDC_RADIO_AA                    1246
#define IDC_BUTTON3                     1247
#define IDC_BTN_AASET                   1247
#define IDC_CHECK1                      1248
#define IDC_CHECK_LED                   1248
#define IDC_CHECK2                      1249
#define IDC_CHECK_BUZZER                1249
#define IDC_CHECK_LED2                  1249
#define IDC_CHECK3                      1250
#define IDC_CHECK_FILTER                1250
#define IDC_BTN_SETLB                   1251
#define IDC_BUTTON5                     1252
#define IDC_BTN_GETLB                   1252
#define IDC_EDIT3                       1253
#define IDC_EDIT_AUTOINTERVAL           1253
#define IDC_RADIO4                      1254
#define IDC_RADIO_TYPE6B                1254
#define IDC_RADIO5                      1255
#define IDC_RADIO_TYPE6C                1255
#define IDC_COMBO2                      1256
#define IDC_COMBO_AREA                  1256
#define IDC_COMBO3                      1257
#define IDC_COMBO_DATAOUTTYPE           1257
#define IDC_EDIT4                       1258
#define IDC_EDIT_HEADADDR               1258
#define IDC_EDIT5                       1259
#define IDC_EDIT_LEN                    1259
#define IDC_EDIT6                       1260
#define IDC_EDIT_FILTERWINDOW           1260
#define IDC_BUTTON4                     1261
#define IDC_BTN_GOBACK                  1261

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1262
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
